name: Python application

on:
  push:
    branches: [ "TRF-35-Develop-data-analytics-framework" ]
  pull_request:
    branches: [ "TRF-35-Develop-data-analytics-framework" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pandas
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint analytics folder only
      run: |
        flake8 analytics/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 analytics/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest analytics/test_analysis.py